### ISSUE TITLE
strato debian10 exim

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/ansible#81]
Strato tends to deliver its debian10 image with a preinstalled [exim](https://wiki.debian.org/Exim), that provokes a conflict with out role [ffh.simplemail](https://github.com/freifunkh/ansible/blob/6a83b64206cafe5abb88ce61e18f8c39f644867b/roles/ffh.simple_mail/tasks/main.yml#L22).

Currently I'm trying to ged rid of this issue in my preprovision script for my testnode sn07.

What do you think about a resolution within the ansible repo?
Like a task in simplemail to purge everything exim4-related before trying to install ssmtp?

Feedback welcome, have a nice Sunday.

**Comment by 1977er** [comment]
Something like:
```
- name: "Sideload ssmtp if necessary"
  when: ssmtp_check_deb.rc == 1
  block:
  - name: "Purge MTAs other than ssmtp"
    apt:
      state: "absent"
      pkg:
      - "postfix"
      - "exim4"
  - name: "Download ssmtp"
    get_url:
...
```
